--- #YAML:1.0
name:               Acme-Can\'t
version:            0.01
abstract:           Determine whether your object can B<NOT> call a given method.
author:
    - Kent Cowgill <kent@c2group.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
